### ISSUE TITLE
Убрать из календаря с расписанием занятий субботы и воскресенья

### ISSUE THREAD

**Issue by NitrocinEagle** [pc-mist/web_course#3]
Календарь сделан с помощью js фреймфорка fullCalendar.js. Отыщи скрипт, который формирует календарь и узнай, как убрать субботу и воскресенье. Если есть желание, можешь разобраться, как он работает. 
Также исправь названия месяцев 'οюнь', 'οюль'

**Comment by pm-str** [comment]
т.е. исключить все дни субботы и воскресенья?

**Comment by NitrocinEagle** [comment]
Да. Субботы и воскресенья не должно быть в расписании
